### ISSUE TITLE
cli not found

### ISSUE THREAD

**Issue by Misery42** [joshstevens19/ethereum-abi-types-generator#27]
After installation with $ npm install ethereum-abi-types-generator --save-dev
It says:
bash: abi-types-generator: command not found

Whats wrong? What to do?

**Comment by Misery42** [comment]
Okay got it. It must be in the scripts section of the package.json
It will not work on the cmd.

**Comment by joshstevens19** [comment]
The command have to be executed where it is installed. If you used the -g you be able to use it globally but as readme says best to use it in each package and use the script sections to generate it. Glad you sorted it
