### ISSUE TITLE
Lint warnings in generated typescript?

### ISSUE THREAD

**Issue by altay** [joshstevens19/ethereum-abi-types-generator#29]
Hey Josh, thanks for the great library. I'm getting some warnings from the generated typescript (see image). Are these known issues?

<img width="885" alt="Screen Shot 2021-12-28 at 3 06 41 AM" src="https://user-images.githubusercontent.com/82309/147544092-7f705512-a46d-41b2-b30c-186f5e649169.png">

**Comment by joshstevens19** [comment]
Hey this is your linter on the file itself you should ignore it from your lints and should all go!
