### ISSUE TITLE
Ethers' `queryFilter`

### ISSUE THREAD

**Issue by ThomasdenH** [joshstevens19/ethereum-abi-types-generator#38]
First of all, thanks for this tool, it's great!

Just so you know, I think the [`queryFilter`](vaultsReceived) method is missing from contracts in Ethers.js. I've linked the documentation.

**Comment by vipergtsrz** [comment]
@joshstevens19 Any update on this? Not sure how to filter historical events with the ethers_v5 provider without the queryFilter method.

**Comment by vipergtsrz** [comment]
@joshstevens19 I opened a PR to fix this on #44 

Please review and merge so we can call this method with TS. Thanks!

@ThomasdenH
